version: "3.0"

services:
  master_db:
    build: ./master
    container_name: master_db
    volumes: 
      - ./master/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=123
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - psql_network
  
  slave_db:
    build: ./slave
    container_name: slave_db
    depends_on:
      - master_db
    environment:
      - POSTGRES_PASSWORD=123
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - psql_network
      

networks:
  psql_network:
    driver: bridge
