version: "3.0"

services:
  master_db:
    build: ./master
    container_name: master_db
    volumes: 
      - ./master/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRES_PASSWORD=123
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - psql_network
  
  slave_db:
    build: ./slave
    container_name: slave_db
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRES_PASSWORD=123
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - psql_network
      

networks:
  psql_network:
    driver: bridge
